format = """
[](#BA1861)\
$username\
[](bg:#DB4678 fg:#BA1861)\
$directory\
[](fg:#DB4678 bg:#E87D8C)\
$git_branch\
$git_status\
[](fg:#E87D8C bg:#89ABCE)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#89ABCE bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#ab0cb6)\
$time\
[ ](fg:#ab0cb6)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#BA1861 fg:#FFFFFF"
style_root = "bg:#BA1861 fg:#FFFFFF"
format = '[$user ]($style)'

[directory]
style = "bg:#DB4678 fg:#FFFFFF"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#89ABCE fg:#FFFFFF"
format = '[[ $symbol ($version) ](bg:#89ABCE fg:#FFFFFF)]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A fg:#FFFFFF"
format = '[[ $symbol $context ](bg:#06969A fg:#FFFFFF)]($style) $path'

[elixir]
symbol = " "
style = "bg:#89ABCE fg:#FFFFFF"
format = '[[ $symbol ($version) ](bg:#89ABCE fg:#FFFFFF)]($style)'

[elm]
symbol = " "
style = "bg:#89ABCE fg:#FFFFFF"
format = '[[ $symbol ($version) ](bg:#89ABCE fg:#FFFFFF)]($style)'

[git_branch]
symbol = ""
style = "bg:#E87D8C fg:#FFFFFF"
format = '[[ $symbol $branch ](bg:#E87D8C fg:#FFFFFF)]($style)'

[git_status]
style = "bg:#E87D8C fg:#FFFFFF"
format = '[[($all_status$ahead_behind )](bg:#E87D8C fg:#FFFFFF)]($style)'

[golang]
symbol = " "
style = "bg:#89ABCE fg:#FFFFFF"
format = '[[ $symbol ($version) ](bg:#89ABCE fg:#FFFFFF)]($style)'

[haskell]
symbol = " "
style = "bg:#89ABCE fg:#FFFFFF"
format = '[[ $symbol ($version) ](bg:#89ABCE fg:#FFFFFF)]($style)'

[java]
symbol = " "
style = "bg:#89ABCE fg:#FFFFFF"
format = '[[ $symbol ($version) ](bg:#89ABCE fg:#FFFFFF)]($style)'

[julia]
symbol = " "
style = "bg:#89ABCE fg:#FFFFFF"
format = '[[ $symbol ($version) ](bg:#89ABCE fg:#FFFFFF)]($style)'

[nodejs]
symbol = ""
style = "bg:#89ABCE fg:#FFFFFF"
format = '[[ $symbol ($version) ](bg:#89ABCE fg:#FFFFFF)]($style)'

[nim]
symbol = " "
style = "bg:#89ABCE fg:#FFFFFF"
format = '[[ $symbol ($version) ](bg:#89ABCE fg:#FFFFFF)]($style)'

[rust]
symbol = ""
style = "bg:#89ABCE fg:#FFFFFF"
format = '[[ $symbol ($version) ](bg:#89ABCE fg:#FFFFFF)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#ab0cb6 fg:#FFFFFF"
format = '[[ ❤️ $time ](bg:#ab0cb6 fg:#FFFFFF)]($style)'

